### PR TITLE
Don't panic on second call if server is off

### LINKED ISSUE #52: Panic on second call if server is off
Hello,

When we try to make requests on a shutdown server, the program panic at the second call.
Strangely, the first call works well (returns an `Err`) but not the second.

Here is an example :

```rust
use eventstore::{Connection, Credentials};

#[tokio::main]
async fn main() {
    let connection = Connection::builder()
        .with_default_user(Credentials::new("admin", "changeit"))
        .single_node_connection("127.0.0.1:1113".parse().unwrap())
        .await;

    println!("{:?}", connection.read_all().execute().await);
    println!("{:?}", connection.read_all().execute().await);
}
```

And the execution output :

```
Err(Aborted)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/eventstore-0.7.4/src/internal/operations.rs:939:9
```

I expected to get an `Err` on each requests, am I misunderstanding something ?

Thank you !

### PR DESCRIPTION
**Pull request by chapa**
Transform `oneshot::Canceled` errors to `OperationError::ConnectionHasDropped` and forward them to the caller so it can handle them properly.

Previous `.unwrap()` used to cause panicking when two operations was requested on a shutdown server.

Fix #52 

### Additional information

I don't know why, but I wasn't able to test writing operations. They were all blocking the test that couldn't finish, not even a panic :thinking: 
- `connection.write_events`
- `connection.start_transaction`
- `transaction.write`
- `transaction.commit`
- `connection.delete_stream`
- `connection.update_persistent_subscription`
- `connection.delete_persistent_subscription`

Also, the test `offline_server_test` I wrote displays this "error" :
```
ERROR eventstore::internal::driver] Maximum reconnection attempt count reached (0)!
```
I don't know if it's disturbing ?

Another detail, we can't change the `Driver::reconnect_delay` with the `ConnectionBuilder` API, which makes the test 3 seconds too long... :yum:

### CODE REVIEW

**Comment by YoEight** [comment]
Hi @chapa!
I just saw that PR, it didn't show up in my notification feed (I was about to fix that specific issue 😄).

File: src/internal/operations.rs [hunk 1]
```diff
@@ -179,7 +179,7 @@ impl WriteEvents {
             Ok(()) as std::io::Result<()>
         });
 
-        promise.await.unwrap()
+        promise.await.map_err(|_| types::OperationError::ConnectionHasDropped)?
```
Comment (YoEight) [inline src/internal/operations.rs]: `ConnectionHasDropped` has a different meaning internally, In this situation, a better error would be `ConnectionClosed`. That enum variant doesn't exist yet and I suggest to add it.

File: src/internal/operations.rs [hunk 2]
```diff
@@ -289,7 +289,7 @@ impl ReadEvent {
...
```
Comment (YoEight) [inline src/internal/operations.rs]: Same as above.

File: src/internal/operations.rs [hunk 3]
```diff
@@ -409,7 +409,7 @@ impl TransactionStart {
...
```
Comment (YoEight) [inline src/internal/operations.rs]: Same as above.

File: src/internal/operations.rs [hunk 4]
```diff
@@ -663,7 +663,7 @@ impl TransactionCommit {
...
```
Comment (YoEight) [inline src/internal/operations.rs]: Same as above.

File: src/internal/operations.rs [hunk 5]
```diff
@@ -811,7 +811,7 @@ impl ReadStreamEvents {
...
```
Comment (YoEight) [inline src/internal/operations.rs]: Same as above.

File: src/internal/operations.rs [hunk 6]
```diff
@@ -936,7 +936,7 @@ impl ReadAllEvents {
...
```
Comment (YoEight) [inline src/internal/operations.rs]: Same as above.

File: src/internal/operations.rs [hunk 7]
```diff
@@ -1063,7 +1063,7 @@ impl DeleteStream {
...
```
Comment (YoEight) [inline src/internal/operations.rs]: Same as above.

File: src/internal/operations.rs [hunk 8]
```diff
@@ -1864,7 +1864,7 @@ impl CreatePersistentSubscription {
...
```
Comment (YoEight) [inline src/internal/operations.rs]: Same as above.

File: src/internal/operations.rs [hunk 9]
```diff
@@ -2053,7 +2053,7 @@ impl DeletePersistentSubscription {
...
```
Comment (YoEight) [inline src/internal/operations.rs]: Same as above.

File: tests/integration.rs [hunk 10]
```diff
@@ -647,6 +647,33 @@ pub mod tcp {
         })
         .unwrap();
     }
+
+    #[test]
+    fn offline_server_test() {
+        block_on(async {
+            let host = std::env::var("EVENTSTORE_HOST").unwrap_or("127.0.0.1".to_string());
+            let conn_str = format!("{}:1114", host); // Be sure your server doesn't run on port 1114
```
Comment (YoEight) [inline tests/integration.rs:655]: The server runs on 1113.

File: tests/integration.rs [hunk 11]
```diff
@@ -647,6 +647,33 @@ pub mod tcp {
         })
         .unwrap();
     }
+
+    #[test]
+    fn offline_server_test() {
```
Comment (YoEight) [inline tests/integration.rs:652]: I don't see how `offlive_server_test` captures the issue. The problem happens only when the server is offline and the client gave up trying to reconnect. I don't think a simple unit test will work here. We need to move to https://github.com/testcontainers/testcontainers-rs.

I don't ask you doing this in this PR (but feel free to do it if you want 😃 )

File: src/internal/operations.rs [hunk 12]
```diff
@@ -1972,7 +1972,7 @@ impl UpdatePersistentSubscription {
...
```
Comment (YoEight) [inline src/internal/operations.rs]: Same as above.

**Review by YoEight — CHANGES_REQUESTED** [review]

**Comment by YoEight** [comment]
Thank you for your PR. It looks good minor a few remarks. ~I let a comment about the test. If you don't want to do it, please remove that test. A proper test would need a better testing infrastructure to capture that particular situation.~

Could you change the PR title, so it reflects the issue you opened earlier #52, please?

Somehow, no GitHub Actions were triggered. Let's hope your next commit push will trigger them.

File: tests/integration.rs (hunk 11 above)
Comment (YoEight) [reply tests/integration.rs:652]: I think I understand what you did. You purposely choose a wrong port to trigger the issue at the first attempt. Forget what I said earlier then, it's a good idea!

**Comment by YoEight** [comment]
I made `reconnect_delay` configurable now https://github.com/YoEight/eventstore-rs/pull/55, if you want to use it.

**Comment by chapa** [comment]
Hi, thanks for your feedback, I changed the PR title and did the modifications you suggests :wink:

**Comment by chapa** [comment]
Strangely though, Github Actions doesn't seem to have been triggered this time either :thinking:

**Comment by YoEight** [comment]
Hi @chapa,

I fixed the GitHub Action issue however you now have to rebase your branch from the master branch so your pull request can enjoy it. I apologise for the inconvenience.

**Comment by YoEight** [comment]
Thank you for your work @chapa !

**Comment by chapa** [comment]
You're welcome :wink:
